webHookURL = "" -- The Webhook link to post too.
local DISCORD_NAME = "Report Bot" -- Changes the name of the bot (default : Report Bot)
local DISCORD_IMAGE = "https://www.realbookies.com/wp-content/uploads/2019/03/reporting-analytics_60.png" -- Any Image URL works
local role = "588135194008092687" -- Must be a role id
enableReport = true -- Enable /report command

local role = "<@&"..role..">"

if enableReport then
    RegisterCommand("report", function(source, args, rawCommand)
        local user = tonumber(args[1])
        local msg = table.concat(args, " ", 2)
        local username = GetPlayerName(user)
		local reporter = GetPlayerName(source)
		if username == nil then
			print("Please assure that the ID is correct (invalid or no ID detected)")
		else
			color = 16711680
			print("The User".. username .. " Was Reported to Staff!")
			sendMessage("The User ["..user.."] ".. username .. " Was Reported For: ","**".. msg.."**", color, reporter)
		end
    end)
end

function sendMessage(username, msg, color, reporter)
  local connect = {
        {
            ["color"] = color,
            ["title"] = "**".. username .."**",
            ["description"] = msg,
            ["footer"] = {
            ["text"] = "Report Generated By : "..reporter.. ".",
            },
        }
    }
	PerformHttpRequest(webHookURL, function(err, text, headers) end, 'POST', json.encode({username = DISCORD_NAME, content = role , embeds = connect, avatar_url = DISCORD_IMAGE}), { ['Content-Type'] = 'application/json' })
end
