webHookURL = "https://discordapp.com/api/webhooks/594213184827686924/WMy3SdUFpotiUX-fvskHQ29ZsQoxHOE0Snw_ynVLXTyvX_tbDf0cLVjcsJNDtVXwkvq4" -- The Webhook link to post too.
local DISCORD_NAME = "Report Bot" -- Changes the name of the bot (default : Report Bot)
local DISCORD_IMAGE = "https://www.realbookies.com/wp-content/uploads/2019/03/reporting-analytics_60.png" -- Any Image URL works
enableReport = true -- Enable /report command

if enableReport then
    RegisterCommand("report", function(source, args, rawCommand)
        local user = tonumber(args[1])
        local msg = table.concat(args, " ", 2)
        local username = GetPlayerName(user)
		local reporter = GetPlayerName(source)
        color = 1127128
		sendMessage("The User ".. username .. " Was Reported For: ","**".. msg.."**", color, reporter)
    end)
end

function sendMessage(username, msg, color, reporter)
  local connect = {
        {
            ["color"] = color,
            ["title"] = "**".. username .."**",
            ["description"] = msg,
            ["footer"] = {
            ["text"] = "Report Generated By : "..reporter.. ".",
            },
        }
    }
	PerformHttpRequest(webHookURL, function(err, text, headers) end, 'POST', json.encode({username = DISCORD_NAME, embeds = connect, avatar_url = DISCORD_IMAGE}), { ['Content-Type'] = 'application/json' })
end